name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2  # <-- Cambio aquí

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image
      env:
        IMAGE_URI: 839088212270.dkr.ecr.us-east-2.amazonaws.com/quantafrontend
      run: |
        docker build -t $IMAGE_URI:latest -t $IMAGE_URI:${{ github.sha }} .
        docker push $IMAGE_URI:latest
        docker push $IMAGE_URI:${{ github.sha }}

